### ISSUE TITLE
persistent libc.txt.gz for glibc_function_args

### ISSUE THREAD

**Issue by aliencaocao** [hugsy/gef-extras#106]
**Is your feature request related to a problem? Please describe.**
Im always frustrated when I have to download https://www.gnu.org/software/libc/manual/text/libc.txt.gz everytime I work on a new project/switch to a different dir. I hope there can be a way to read the extracted json from a fixed path in env var.

**Describe the solution you'd like**
Use the path defined in `context.libc_args_path` in `gef config`.

```
file libc.txt.gz cannot be found. download it from https://www.gnu.org/software/libc/manual/text/libc.txt.gz
Traceback (most recent call last):
  File "/root/.config/gef-extras/scripts/libc_function_args/tables/generate_glibc_args_json.py", line 56, in <module>
    fh = gzip.open(file_name, "r")
  File "/usr/lib/python3.10/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib/python3.10/gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'libc.txt.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.config/gef-extras/scripts/libc_function_args/tables/generate_glibc_args_json.py", line 63, in <module>
    sys.exit(-1)
  File "/root/.gef-2024.01.py", line 446, in FakeExit
    raise RuntimeWarning
RuntimeWarning
```

**Comment by therealdreg** [comment]
the same bug: #107 

@hugsy Is aware of the cause and is working on it

**Comment by aliencaocao** [comment]
Oh so this is supposed to be persistent but it is a bug that it is not?

**Comment by therealdreg** [comment]
The current code is not behaving as it should, so it is a bug.

![image](https://github.com/hugsy/gef-extras/assets/9882181/cd7b7cfa-00c7-43df-9a1c-f4a11e93eda7)

As you can see, the libc and JSON files are already included, but it fails to find the path, which is why it requires you to specify the route.

**Comment by therealdreg** [comment]
@aliencaocao can you test a simple fix?

```
cd ~/.config/gef-extras/scripts/libc_function_args/tables
wget https://www.gnu.org/software/libc/manual/text/libc.txt.gz
```

Edit: ~/.config/gef-extras/scripts/libc_function_args/tables/generate_glibc_args_json.py

replace old "file_name = libc.txt.gz"

with this:

```
file_name = pathlib.Path(inspect.getfile(inspect.currentframe())).parent.resolve() / "libc.txt.gz"
```

Edit ~/.config/gef-extras/scripts/libc_function_args/__init__.py

replace GLIBC_FUNCTION_ARGS_CURRENT_FILE =
and 
GLIBC_FUNCTION_ARGS_CURRENT_DIRECTORY =

with this:
``` 
GLIBC_FUNCTION_ARGS_CURRENT_FILE = pathlib.Path(inspect.getfile(inspect.currentframe())).parent.resolve()
GLIBC_FUNCTION_ARGS_CURRENT_DIRECTORY = pathlib.Path(inspect.getfile(inspect.currentframe())).parent.resolve()
```

This works now as expected?

**Comment by aliencaocao** [comment]
I did the mods, launched gef once and saw the json written messages, then deleted the txt.gz, still same error come out.

**Comment by aliencaocao** [comment]
If I switch to the different dir without deleting the txt.gz, it works fine but it seem to be extracting it every time i run gef which is not very necessary.
Also, when I run gef in the same dir as `tables`, I get `file x86_64.json exists, overwrite? [y/N]` for both json.

**Comment by therealdreg** [comment]
Let's tackle this step by step. 

First, I want to address the path issue, and then we'll move on to the other matters.

If we keep the files in the tables/ directory, everything works as you would expect, right?

**Comment by aliencaocao** [comment]
Yes it does work if i keep the txt.gz, but that was not the reason I opened the issue as I thought the json itself should be cached and reused. Seems like this is a feature request instead of a bug then

**Comment by therealdreg** [comment]
> I have to download https://www.gnu.org/software/libc/manual/text/libc.txt.gz everytime I work on a new project/switch to a different dir

**I have to download https://www.gnu.org/software/libc/manual/text/libc.txt.gz everytime I work on a new project/switch to a different dir**

This should not happen, and this is my fix :D

**Comment by therealdreg** [comment]
path issue fixed #109

**Comment by therealdreg** [comment]
I want to make sure everything works well. Can you test the latest dev versions of gef-extras and gef and let me know if everything now works as you expect, please? #111 https://github.com/hugsy/gef/pull/1093

@aliencaocao @DimSumCodes 

https://github.com/hugsy/gef-extras/archive/refs/heads/main.zip
https://github.com/hugsy/gef/archive/refs/heads/main.zip

**Comment by DimSumCodes** [comment]
I have no idea how but all of a sudden it fixed itself, I didn’t even
update anything but I got you I’ll update and see if I still have the same
issue.

**Comment by DimSumCodes** [comment]
Just checked it, works perfectly doesn't generate a new file in my active directory and doesn't have any issues referencing the files.

**Comment by hugsy** [comment]
Great work on fixing this @therealdreg 🎉
