### ISSUE TITLE
TypeError NoneType

### ISSUE THREAD

**Issue by b0x41s** [hugsy/gef-extras#25]
TypeError: 'NoneType' object is not iterable
───────────────────────────── Detailed stacktrace ──────────────────────────────
↳ File "/home/b0x41s/gef-extras/scripts/skel.py", line 68, in do_invoke()

* GDB: 7.11.1
* Python: 3.5.2 - final
* OS: Linux - 4.15.0-106-generic (x86_64)

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

**Comment by nnewram** [comment]
probably needs to check if gdb.breakpoints() returns None, if so make bkps = []?

**Comment by hugsy** [comment]
This issue should have been fixed by 0ad666a 

Please update your repo and try again. If it fails, provide a complete debug output (`gef config gef.debug 1`).
Thanks,
