### ISSUE TITLE
RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility.

### ISSUE THREAD

**Issue by David-Reguera-Garcia-Dreg** [hugsy/gef-extras#29]
$ gdb /bin/ls
GEF for linux ready, type `gef' to start, `gef config' to configure
80 commands loaded for GDB 10.1 using Python engine 3.9
[+] Configuration from '/home/kali/.gef.rc' restored
<frozen importlib._bootstrap>:228: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:228: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:228: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:228: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
[+] 29 extra commands added from '/home/kali/gef-extras/scripts'
Reading symbols from /bin/ls...
(No debugging symbols found in /bin/ls)

$ uname -a
Linux kali 5.9.0-kali1-amd64 #1 SMP Debian 5.9.1-1kali2 (2020-10-29) x86_64 GNU/Linux
           
# How to reproduce:

Download the last Kali-Linux-2020.4-vmware-amd64

$ sudo apt-get update

$ sudo apt install git cmake gcc g++ pkg-config libglib2.0-dev python3-pip build-essential python3 python3-dev gdb libcapstone3 libcapstone-dev cmake

The last kali use python3.9 in GDB (GDB 10.1 using Python engine 3.9) then:

$ sudo python3.9 -m pip install unicorn capstone filebytes keystone-engine ropper rpyc retdec-python

$ sh -c "$(wget http://gef.blah.cat/sh -O -)"

$ wget -q -O- https://github.com/hugsy/gef/raw/master/scripts/gef-extras.sh | sh

Now use: $ gdb /bin/ls

---

**If I remove ida_interact.py I dont see this warning**

**Comment by hugsy** [comment]
This is not gef related.

https://github.com/python-greenlet/greenlet/issues/178
