### ISSUE TITLE
"vis_heap_chunks"-like display of heap like in pwndbg

### ISSUE THREAD

**Issue by OevreFlataeker** [hugsy/gef-extras#30]
I am using pwndbg in addition to GEF and I really like the "vis_heap_chunks" feature of pwndbg to visualize the heap. (https://browserpwndbg.readthedocs.io/en/docs/commands/heap/vis_heap_chunks/) 

The color printout with ASCII-art arrows that annotate the various heap chunks is very helpful in my opinion.

I'd love to see that kind of display in GEF as well :-D

Thanks for considering!

**Comment by hugsy** [comment]
Done (by ba5fa24), looks like:

![image](https://user-images.githubusercontent.com/590234/107161902-99985a00-6954-11eb-9513-1f63848f9559.png)

**Comment by hugsy** [comment]
Thanks @OevreFlataeker & @Kyle-Kyle for the suggestion.

Happy to take some insights/PRs, cheers!
