### ISSUE TITLE
Error Codes

### ISSUE THREAD

**Issue by khaoticdude** [hugsy/gef-extras#34]
As discussed on Discord:

* !error feature similar to WinDbg
* converts a value (dec or hex) and/or a register to its verbose output (perror style)

**Comment by hugsy** [comment]
@khaoticdude If you still plan on working on this, you can use `strerror` to avoid collecting manually all the Linux error codes:

```python
from ctypes import *
libc = CDLL("libc.so.6")
libc.strerror.restype = c_char_p
libc.strerror.argtypes = [c_uint32,]
EPERM = 1
c_s = c_char_p( libc.strerror( EPERM ) ) 
print("%d -> %s" % (EPERM, c_s.value))
```

Will output something easy to plug into gef.

```
1 -> b'Operation not permitted'
```

Ping us if you have questions

**Comment by hugsy** [comment]
Done with d255e3c

**Comment by Grazfather** [comment]
If you're too slow @hugsy will just do it for you :D

**Comment by khaoticdude** [comment]
Yeah I saw lolol. Much appreciated neverthelessOn Apr 16, 2021 12:40, Grazfather ***@***.***> wrote:
If you're too slow @hugsy will just do it for you :D
