### ISSUE TITLE
Command 'visualize-libc-heap-chunks' failed to execute properly, reason: type object 'GlibcArena' has no attribute 'TCACHE_MAX_BINS'

### ISSUE THREAD

**Issue by ebubekirtrkr** [hugsy/gef-extras#38]
I installed gef-extras via install script but when I want to use `vis` command `Command 'visualize-libc-heap-chunks' failed to execute properly, reason: type object 'GlibcArena' has no attribute 'TCACHE_MAX_BINS' ` error occurs. Is there any suggestions?

**Comment by hugsy** [comment]
Can you enable the debug mode and paste here the stack trace of the error ?

**Comment by hugsy** [comment]
No need, there was a trivial typo, fixed by  61800f8
Just update `gef-extras` and you should be ok.

**Comment by ebubekirtrkr** [comment]
We should also change [line 38](https://github.com/hugsy/gef-extras/blob/master/scripts/visualize_heap.py#L33) in script to 
```py
tcache_addr = GlibcHeapTcachebinsCommand.find_tcache()
chunk,count = GlibcHeapTcachebinsCommand.tcachebin(tcache_addr,i)
```
because `GlibcArena` has no member `tcachebin`

**Comment by hugsy** [comment]
Good call, should be fixed

**Comment by hugsy** [comment]
For tracking : 
- dad2844
