### ISSUE TITLE
windbg alias p conflicts with p/x, p/d

### ISSUE THREAD

**Issue by Kileak** [hugsy/gef-extras#39]
I use p/x commands a lot to show dec/hex/etc. values, but after including `gef-extras` those don't work anymore, since `p` is aliased by windbg to `nexti`

Original gdb
```
(gdb) p/x 1000
$1 = 0x3e8
(gdb) p/d 0xdead
$2 = 57005
```

Gef with gef-extras
```
gef➤  p/x 1000
Python Exception <class 'gdb.error'> The program is not being run.: 
Error occurred in Python: The program is not being run.
gef➤  p/d 0xdead
Python Exception <class 'gdb.error'> The program is not being run.: 
Error occurred in Python: The program is not being run.
```

**Comment by hugsy** [comment]
It's sortta by design to respect the commands syntax from WinDbg. With this plugin `p` is not really necessary as you can use the `da/db/dw/dd/dq` or `x` commands
