### ISSUE TITLE
unable to use syscall-args when gef-extras configured in python3.9

### ISSUE THREAD

**Issue by neocxf** [hugsy/gef-extras#49]
Hi, I have installed the gef-extras using the install script way, and the script finished successfully. But when I invoke the `syscall-args` function, 
![image](https://user-images.githubusercontent.com/12878595/153789082-b865d3dc-895e-425f-912d-e4454bd70d2e.png)

I am using the python3.9 environment. I have already googled all over the internet, but found nothing really useful tips. Is this a compatible issue due to my py environtment?

**Comment by daniellimws** [comment]
Hi can you run the `version` command and share the output here. Or you can join our [Discord server](https://discord.gg/HCS8Hg7) for a quicker response.

**Comment by hugsy** [comment]
If you enable the debug output (`gef config gef.debug 1`) what message do you get after running the command?

**Comment by neocxf** [comment]
@daniellimws  This is my `version` output
![image](https://user-images.githubusercontent.com/12878595/153814221-03c9a605-b10b-4eec-a5a5-80e879d9c60b.png)

@hugsy It's a bit weired. Everytime I set the gef debug using  `gef config gef.debug 1` command, I got a empty screen, even lose all my `context` output. Literally I can't continue my debug session
![image](https://user-images.githubusercontent.com/12878595/153814936-a49b791c-4493-4686-9441-d5d94f296e20.png)

**Comment by neocxf** [comment]
detail of the error

![image](https://user-images.githubusercontent.com/12878595/153980668-174b536a-6464-4228-8487-742a4c0c9383.png)

**Comment by hugsy** [comment]
My bet would be that the path given for the folder where the syscall arg files are is wrong. I  have just retested the command and it works just fine.

**Comment by hugsy** [comment]
Fixed
