### ISSUE TITLE
source syntax highlight

### ISSUE THREAD

**Issue by JaewonHur** [hugsy/gef-extras#55]
Hi, I'm new to gef-extras.
I found this repo while finding source code syntax highlighting for gef.

So, I installed it and successfully ran gef without any error.
But the output source code seems same (not syntax highlighted).

I used the dev branch since I had an issue with ABC, and I just followed all the instructions.
Is there any thing I did wrong? or did I misunderstand this repository?

**Comment by hugsy** [comment]
You need to make sure you use the same branch for `gef` and `gef-extras`: see https://github.com/hugsy/gef-extras/issues/48#issuecomment-1075981878
