### ISSUE TITLE
Install script fails to pull all dependencies

### ISSUE THREAD

**Issue by 0xricksanchez** [hugsy/gef-extras#70]
* [x] Did you use the latest version of GEF from `dev` branch?
* [x] Is your bug specific to GEF (not GDB)? - Try to reproduce it running `gdb -nx`
* [x] Did you search through the [documentation](https://github.com/hugsy/gef/) first?
* [x] Did you check [issues](https://github.com/hugsy/gef/issues) (including
  the closed ones) - and the [PR](https://github.com/hugsy/gef/pulls)?

### Step 1: Describe your environment

* Operating System / Distribution: Arch Linux
* Architecture: x86_64
* GEF version (including the Python library version) run `version` in GEF:

```
gef>  version
GEF: (Standalone)
Blob Hash(/home/raven/.gef-430d9d3f7efab6e55215c07bd1694c3a4c4cb6cd.py): 606f6ec058080de59f01192f5860eb5d7a51ea94
SHA256(/home/raven/.gef-430d9d3f7efab6e55215c07bd1694c3a4c4cb6cd.py): 2033abfc7e77d9a08de39b38bfee868808a7fb2d04ac6d39a0972959b06f403b
GDB: 12.1
GDB-Python: 3.10
```

### Step 2: Describe your problem

Running gef after installing gef-extras leaves me with this:

```
> gdb
GEF for linux ready, type `gef' to start, `gef config' to configure
90 commands loaded and 5 functions added for GDB 12.1 in 1.38ms using Python engine 3.10
Traceback (most recent call last):
  File "/home/raven/.config/gef-extras/scripts/assemble.py", line 9, in <module>
    import keystone
ModuleNotFoundError: No module named 'keystone'
Traceback (most recent call last):
  File "/home/raven/.config/gef-extras/scripts/ropper.py", line 9, in <module>
    import ropper
  File "/home/raven/.config/gef-extras/scripts/ropper.py", line 12, in <module>
    @register
NameError: name 'register' is not defined
[+] 36 extra commands added from '/home/raven/.config/gef-extras/scripts' in 0.11 seconds
```
Cause:
The installation script for the extras (https://raw.githubusercontent.com/hugsy/gef/main/scripts/gef-extras.sh) currently only installs the `requirements.txt` from `/docs`, which is incomplete. The other `requirements.txt` in the root of this repo seems to be ignored (even though it's having way more requirements listed). 

Probably makes sense to unify those two files: #69 (nice)

**Comment by hugsy** [comment]
Ok got, the problem comes from the wrong `pip install` command in the script in gef itself. I will fix it. It is important to keep different requirements because the requirements of building the docs in gef-extras is not necessary for having the command running.

**Comment by hugsy** [comment]
Fixed by https://github.com/hugsy/gef/commit/b2458d6c760d1c5643f0f7de10642afe3857779e

**Comment by 0xricksanchez** [comment]
Sure that should fix this just fine :). I'll close the issue and my PR
