### ISSUE TITLE
`visualize-heap` is broken

### ISSUE THREAD

**Issue by hugsy** [hugsy/gef-extras#76]
Follow-up on https://github.com/hugsy/gef/issues/854 to address the bugs specific to `visualize-heap`.

Depends on:
 * https://github.com/hugsy/gef/pull/869

Also cc @0xricksanchez

**Comment by 0xricksanchez** [comment]
@hugsy Analogously, to what I have commented on https://github.com/hugsy/gef/issues/854

**Debian Container + GLIBC 2.34**

![image](https://user-images.githubusercontent.com/17012133/177959204-d3317b51-a540-42ae-b17a-3a4d6533ba3d.png)

----

**Arch + GLIBC 2.35**

![image](https://user-images.githubusercontent.com/17012133/177959585-31173b16-593a-45f0-8d1f-37303b2589d6.png)
